### ISSUE TITLE
One-off EditModeRunner:TestConsumer test failure on first run

### ISSUE THREAD

**Issue by lacostej** [pschraut/UnityHeapExplorer#2] opened 2020-12-30 21:33 UTC
Hello

just to say that I encountered the following test failure when integrating the latest version of the package into one of our project (it builds 4 platforms, and only one failed, a re-run of the job fixed it).

```
ERROR: 'UniRx.Timestamped<WWTK.Backend.UserBackend.UserInfo>[].baseOrElementTypeIndex' = -1 is out of range, ignoring. Details in second line
arrayRank=1, isArray=True, typeInfoAddress=7FB38760DE60, address=1826440F0, memoryreader=MemoryReader, isValueType=False
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:LogFormat(LogType, String, Object[])
UnityEngine.Debug:LogErrorFormat(String, Object[])
HeapExplorer.AbstractMemoryReader:ReadObjectSize(UInt64, PackedManagedType) (at Library/PackageCache/com.oddworm.heapexplorer@5f78736fc6/Editor/Scripts/MemoryReader.cs:447)
HeapExplorer.PackedManagedObjectCrawler:SetObjectSize(PackedManagedObject&, PackedManagedType) (at Library/PackageCache/com.oddworm.heapexplorer@5f78736fc6/Editor/Scripts/PackedTypes/PackedManagedObjectCrawler.cs:595)
HeapExplorer.PackedManagedObjectCrawler:CrawlStatic() (at Library/PackageCache/com.oddworm.heapexplorer@5f78736fc6/Editor/Scripts/PackedTypes/PackedManagedObjectCrawler.cs:488)
HeapExplorer.PackedManagedObjectCrawler:Crawl(PackedMemorySnapshot, List`1) (at Library/PackageCache/com.oddworm.heapexplorer@5f78736fc6/Editor/Scripts/PackedTypes/PackedManagedObjectCrawler.cs:72)
HeapExplorer.PackedMemorySnapshot:Initialize(String) (at Library/PackageCache/com.oddworm.heapexplorer@5f78736fc6/Editor/Scripts/PackedTypes/PackedMemorySnapshotEx.cs:1122)
HeapExplorer.<Capture>d__10:MoveNext() (at Library/PackageCache/com.oddworm.heapexplorer@5f78736fc6/Tests/Editor/Test_Editor.cs:54)
UnityEngine.TestTools.<Execute>d__5:MoveNext() (at Library/PackageCache/com.unity.test-framework@1.1.13/UnityEngine.TestRunner/NUnitExtensions/Attributes/TestEnumerator.cs:31)
UnityEngine.TestTools.<ExecuteEnumerableAndRecordExceptions>d__3:MoveNext() (at Library/PackageCache/com.unity.test-framework@1.1.13/UnityEngine.TestRunner/NUnitExtensions/Commands/EnumerableTestMethodCommand.cs:58)
UnityEngine.TestTools.<ExecuteEnumerable>d__2:MoveNext() (at Library/PackageCache/com.unity.test-framework@1.1.13/UnityEngine.TestRunner/NUnitExtensions/Commands/EnumerableTestMethodCommand.cs:38)
UnityEngine.TestRunner.NUnitExtensions.Runner.<ExecuteEnumerable>d__3:MoveNext() (at Library/PackageCache/com.unity.test-framework@1.1.13/UnityEngine.TestRunner/NUnitExtensions/Runner/UnityLogCheckDelegatingCommand.cs:48)
UnityEngine.TestTools.<ExecuteEnumerable>d__9:MoveNext() (at Library/PackageCache/com.unity.test-framework@1.1.13/UnityEngine.TestRunner/NUnitExtensions/Commands/BeforeAfterTestCommandBase.cs:104)
UnityEngine.TestTools.<ExecuteEnumerable>d__9:MoveNext() (at Library/PackageCache/com.unity.test-framework@1.1.13/UnityEngine.TestRunner/NUnitExtensions/Commands/BeforeAfterTestCommandBase.cs:104)
UnityEngine.TestTools.<ExecuteEnumerable>d__9:MoveNext() (at Library/PackageCache/com.unity.test-framework@1.1.13/UnityEngine.TestRunner/NUnitExtensions/Commands/BeforeAfterTestCommandBase.cs:104)
UnityEngine.TestTools.<ExecuteEnumerable>d__9:MoveNext() (at Library/PackageCache/com.unity.test-framework@1.1.13/UnityEngine.TestRunner/NUnitExtensions/Commands/BeforeAfterTestCommandBase.cs:104)
UnityEditor.TestTools.TestRunner.<PerformWork>d__3:MoveNext() (at Library/PackageCache/com.unity.test-framework@1.1.13/UnityEditor.TestRunner/TestRunner/EditorEnumeratorTestWorkItem.cs:99)
UnityEngine.TestRunner.NUnitExtensions.Runner.<RunChildren>d__16:MoveNext() (at Library/PackageCache/com.unity.test-framework@1.1.13/UnityEngine.TestRunner/NUnitExtensions/Runner/CompositeWorkItem.cs:200)
UnityEngine.TestRunner.NUnitExtensions.Runner.<PerformWork>d__12:MoveNext() (at Library/PackageCache/com.unity.test-framework@1.1.13/UnityEngine.TestRunner/NUnitExtensions/Runner/CompositeWorkItem.cs:76)
UnityEngine.TestRunner.NUnitExtensions.Runner.<RunChildren>d__16:MoveNext() (at Library/PackageCache/com.unity.test-framework@1.1.13/UnityEngine.TestRunner/NUnitExtensions/Runner/CompositeWorkItem.cs:200)
UnityEngine.TestRunner.NUnitExtensions.Runner.<PerformWork>d__12:MoveNext() (at Library/PackageCache/com.unity.test-framework@1.1.13/UnityEngine.TestRunner/NUnitExtensions/Runner/CompositeWorkItem.cs:76)
UnityEngine.TestRunner.NUnitExtensions.Runner.<RunChildren>d__16:MoveNext() (at Library/PackageCache/com.unity.test-framework@1.1.13/UnityEngine.TestRunner/NUnitExtensions/Runner/CompositeWorkItem.cs:200)
UnityEngine.TestRunner.NUnitExtensions.Runner.<PerformWork>d__12:MoveNext() (at Library/PackageCache/com.unity.test-framework@1.1.13/UnityEngine.TestRunner/NUnitExtensions/Runner/CompositeWorkItem.cs:76)
UnityEngine.TestRunner.NUnitExtensions.Runner.<RunChildren>d__16:MoveNext() (at Library/PackageCache/com.unity.test-framework@1.1.13/UnityEngine.TestRunner/NUnitExtensions/Runner/CompositeWorkItem.cs:200)
UnityEngine.TestRunner.NUnitExtensions.Runner.<PerformWork>d__12:MoveNext() (at Library/PackageCache/com.unity.test-framework@1.1.13/UnityEngine.TestRunner/NUnitExtensions/Runner/CompositeWorkItem.cs:76)
UnityEditor.TestTools.TestRunner.EditModeRunner:MoveNextAndUpdateYieldObject() (at Library/PackageCache/com.unity.test-framework@1.1.13/UnityEditor.TestRunner/TestRunner/EditModeRunner.cs:234)
UnityEditor.TestTools.TestRunner.EditModeRunner:TestConsumer() (at Library/PackageCache/com.unity.test-framework@1.1.13/UnityEditor.TestRunner/TestRunner/EditModeRunner.cs:267)
System.Reflection.MonoMethod:InternalInvoke(Object, Object[], Exception&)
System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
System.Reflection.MethodBase:Invoke(Object, Object[])
System.Delegate:DynamicInvokeImpl(Object[])
System.MulticastDelegate:DynamicInvokeImpl(Object[])
System.Delegate:DynamicInvoke(Object[])
UnityEditor.EditorApplication:Internal_CallUpdateFunctions() (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorApplication.cs:310)
```

I didn't investigate further.

I'll monitor and see if it happens again.

Env:  Unity 2019.4.9f1, building for Windows target on a Mac.

Thanks for the great tool. I still find it more useful than the unity memory profiler.

**Comment by pschraut** [comment] 2020-12-31 09:22
Thank you for logging this. It's related to how Unity collects types and I'm afraid I'm unable to fix it. 

I reported this issue in January 2019 and Unity staff replied with "We will be changing this behavior to output all types in the coming versions of Unity", yet the bug-report  was closed with "By Design":
https://forum.unity.com/threads/case-1115544-array-type-baseorelementtypeindex-does-not-point-to-its-element-type.609922/

I just asked in this forum  thread if the behavior has ever changed. Feel free to drop a comment in the forum thread as well.

**Comment by lacostej** [comment] 2021-01-08 16:39
OK. Thanks. Since then I've had a few encounters of issues. Examples:

```
Unhandled log message: '[Assert] Assertion failed on expression: 'cachedObj == out_scripting''. Use UnityEngine.TestTools.LogAssert.Expect
```

```
Unhandled log message: '[Error] Reconstructing native to native object connections. Found 59 invalid instanceIDs.'. Use UnityEngine.TestTools.LogAssert.Expect
```

Do you know about those?

We use Unity's Package Manager to import Heap Explorer by default into one of our project's build. On our projects, we run unit tests (with `-runEditorTests`) before making the platform build, and this triggers the Heap Explorer tests and this one fails.

Ideally I would disable the HeapExplorer Tests. I haven't found a very generic way to do this fitting our current setup. 
Maybe I'll remove the Unity.HeapExplorer.Editor.Tests.dll pre build. Any idea of a better work-around?

**Comment by pschraut** [comment] 2021-01-09 09:59
I know the "Reconstructing native to native object connections" error only ([code](https://github.com/pschraut/UnityHeapExplorer/blob/master/Editor/Scripts/PackedTypes/PackedConnection.cs#L171)). It could be a bug in Unity's memory profiling API, but it's hard to tell without having a memory snapshot to debug and analyze.

I [reported a similar issue](https://issuetracker.unity3d.com/issues/2019-dot-4-packedmemorysnapshot-nativeobjects-dot-gchandleindex-contains-1-always) a while ago, where "nativeObject to gcHandle connections" were wrong, which seems to be fixed in 2019.4.10f1. 

I have to look into how to disable HeapExplorer Tests, because I'm not sure if packages pick up scripting defines specified in player settings. If packages do pick up those scripting defines, I can add a define to exclude HeapExplorer Tests. Do you think HeapExplorer Tests should be included or excluded by default?

**Comment by pschraut** [comment] 2021-01-09 16:46
I've just pushed an update. If you install Heap Explorer 3.6.0 the tests are excluded, unless you specify the `HEAPEXPLORER_ENABLE_TESTS` define in your Player Settings [Scripting Define Symbols](https://docs.unity3d.com/Manual/class-PlayerSettingsStandalone.html#Other) or in a [csc.rsp file](https://docs.unity3d.com/Manual/PlatformDependentCompilation.html).

Please let me know if this works for you.

**Comment by lacostej** [comment] 2021-01-11 18:35
That's great. I think it will fix the issue. I'll report if anything weird happens. Thanks a lot.

**Closed as completed** 2021-01-22 05:01 UTC
